# Generated by Django 4.1.1 on 2022-09-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fare_Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Leg_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rider_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.product')),
                ('from_leg_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='fares.leg_group')),
                ('to_leg_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='fares.leg_group')),
            ],
        ),
        migrations.CreateModel(
            name='Leg_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_to', to='fares.area')),
                ('leg_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.leg_group')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.network')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.product')),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_from', to='fares.area')),
            ],
        ),
    ]
