# Generated by Django 4.1.1 on 2022-09-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg_group',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
