# Generated by Django 4.1.1 on 2022-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0002_alter_leg_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg_group',
            name='ref_id',
            field=models.CharField(default='set me', max_length=128),
        ),
        migrations.AlterField(
            model_name='leg_group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
