# Generated by Django 4.1.1 on 2022-10-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0005_alter_leg_rule_from_area_alter_leg_rule_to_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.RemoveField(
            model_name='network',
            name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='ref_id',
            field=models.CharField(default='set me', max_length=128),
        ),
        migrations.AddField(
            model_name='fare_container',
            name='ref_id',
            field=models.CharField(default='set me', max_length=128),
        ),
        migrations.AddField(
            model_name='network',
            name='ref_id',
            field=models.CharField(default='set me', max_length=128),
        ),
        migrations.AddField(
            model_name='rider_category',
            name='ref_id',
            field=models.CharField(default='set me', max_length=128),
        ),
    ]
