# Generated by Django 4.1.1 on 2022-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0008_fare_container_amount_fare_container_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider_category',
            name='eligibility_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_category',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider_category',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
