# Generated by Django 4.1.1 on 2022-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0009_rider_category_eligibility_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_rule',
            name='duration_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer_rule',
            name='duration_limit_type',
            field=models.CharField(choices=[('0', '1st leg departure to 2nd leg arrival'), ('1', '1st leg departure to 2nd leg departure')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='transfer_rule',
            name='transfer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fare_container',
            name='ref_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rider_category',
            name='ref_id',
            field=models.CharField(max_length=128),
        ),
    ]
