# Generated by Django 4.1.1 on 2022-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0010_transfer_rule_duration_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_rule',
            name='fare_transfer_type',
            field=models.CharField(choices=[('0', 'From leg + transfer price'), ('1', 'From leg + transfer + to leg price'), ('2', 'transfer price only')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='transfer_rule',
            name='duration_limit_type',
            field=models.CharField(choices=[('0', '1st leg departure to 2nd leg arrival'), ('1', '1st leg departure to 2nd leg departure'), ('2', '1st leg arrival to 2nd leg departure'), ('3', '1st leg arrival to 2nd leg arrival')], default='0', max_length=1),
        ),
    ]
