# Generated by Django 4.1.1 on 2022-10-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0011_transfer_rule_fare_transfer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_rule',
            name='fare_transfer_type',
            field=models.CharField(choices=[('0', 'From leg + transfer price'), ('1', 'From leg + transfer + to leg price'), ('2', 'transfer price only')], default='0', max_length=6),
        ),
    ]
