# Generated by Django 4.1.1 on 2022-10-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0012_alter_transfer_rule_fare_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref_id',
            field=models.CharField(default='kk', max_length=128),
        ),
    ]
