# Generated by Django 4.1.1 on 2022-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0014_alter_area_ref_id_alter_fare_container_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leg_group',
            name='id',
        ),
        migrations.AlterField(
            model_name='leg_group',
            name='ref_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref_id',
            field=models.CharField(max_length=128),
        ),
    ]
