# Generated by Django 4.1.3 on 2022-11-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0016_route_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='route_id',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='ref_id',
            new_name='route_short_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='route',
            name='currency',
        ),
        migrations.AddField(
            model_name='route',
            name='network_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.network'),
        ),
    ]
