# Generated by Django 4.1.3 on 2022-11-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0018_alter_stop_parent_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg_rule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leg_rules', to='fares.product'),
        ),
    ]
