# Generated by Django 4.1.1 on 2022-11-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0019_alter_leg_rule_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fares.area')),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='fares.stop')),
            ],
        ),
    ]
