# Generated by Django 4.1.1 on 2022-11-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0020_stop_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='ref_id',
            new_name='area_id',
        ),
    ]
