# Generated by Django 4.1.1 on 2022-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0022_rename_ref_id_area_area_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='as_route',
            field=models.CharField(blank=True, choices=[('0', 'network as route'), ('1', 'do not treat network as  route')], default='1', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='route_long_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
