# Generated by Django 4.1.1 on 2022-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0023_route_as_route_route_route_long_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='as_route',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], default='1', max_length=1, null=True),
        ),
    ]
