# Generated by Django 4.1.7 on 2023-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0024_alter_route_as_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fare_container',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='as_route',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Yes')], default=None, max_length=1, null=True),
        ),
    ]
