# Generated by Django 4.1.7 on 2023-02-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0025_alter_fare_container_amount_alter_route_as_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_rule',
            name='fare_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fares.product'),
        ),
    ]
