# Generated by Django 4.1.7 on 2023-02-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0027_leg_rule_legacy_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leg_rule',
            old_name='legacy_amount',
            new_name='amount',
        ),
    ]
