# Generated by Django 4.1.7 on 2023-02-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0029_alter_leg_rule_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=128)),
                ('tuesday', models.BooleanField(blank=True, null=True)),
                ('wednesday', models.BooleanField(blank=True, null=True)),
                ('thursday', models.BooleanField(blank=True, null=True)),
                ('friday', models.BooleanField(blank=True, null=True)),
                ('saturday', models.BooleanField(blank=True, null=True)),
                ('sunday', models.BooleanField(blank=True, null=True)),
                ('monday', models.BooleanField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=8, null=True)),
                ('end_date', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
